[package]
name = "coppice"
version = "0.1.0"
edition = "2021"
description = "Dynamic programming library for acyclic analytical queries"
license = "MIT"

[dependencies]
merge = "0.1"
quinine = "0.2"
rayon = "1"
umash = "0.6"

[dev-dependencies]
rusty-fork = "0.3"